kind: Service
apiVersion: v1
metadata:
  name: costmatrix
  annotations:
    external-dns.alpha.kubernetes.io/hostname: costmatrix.slateci.net
  labels:
    k8s-app: costmatrix
  # namespace: uchicago-edu
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  # externalIPs:
  # - 192.170.227.230
  selector:
    k8s-app: costmatrix
---
apiVersion: v1
kind: Pod
metadata:
  name: costmatrix  
  labels:
    k8s-app: costmatrix
spec:
  containers:
  - name: cost-matrix-server
    image: atlasanalyticsservice/costmatrix:latest
    ports:
      - containerPort: 80
    livenessProbe:
      httpGet:
        # when "host" is not defined, "PodIP" will be used
        # host: my-host
        # when "scheme" is not defined, "HTTP" scheme will be used. Only "HTTP" and "HTTPS" are allowed
        # scheme: HTTPS
        path: /
        port: 80
        # httpHeaders:
        # - name: X-Custom-Header
        #   value: Awesome
      initialDelaySeconds: 30
      timeoutSeconds: 5
  restartPolicy: Always
