kind: Service
apiVersion: v1
metadata:
  name: costmatrix
  labels:
    k8s-app: costmatrix
  # namespace: uchicago-edu
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  # externalIPs:
  # - 192.170.227.230
  selector:
    k8s-app: costmatrix
---
apiVersion: v1
kind: Pod
metadata:
  name: costmatrix  
  labels:
    k8s-app: costmatrix
spec:
  containers:
  - name: cost-matrix-server
    image: atlasanalyticsservice/costmatrix:latest
    ports:
      - containerPort: 8080
  restartPolicy: Always
