kind: Service
apiVersion: v1
metadata:
  name: costmatrix
  namespace: aaas
  annotations:
    external-dns.alpha.kubernetes.io/hostname: costmatrix.slateci.net
  labels:
    app: costmatrix
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  # externalIPs:
  # - 192.170.227.235
  selector:
    app: costmatrix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: costmatrix-deployment
  namespace: aaas
  labels:
    app: costmatrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: costmatrix
  template:
    metadata:
      labels:
        app: costmatrix
    spec:
      containers:
      - name: cost-matrix-server
        image: atlasanalyticsservice/costmatrix:latest
        ports:
          - containerPort: 80
        # livenessProbe:
        #   httpGet:
        #     path: /last?source=MWT2&destination=AGLT2
        #     port: 80
            # httpHeaders:
            # - name: X-Custom-Header
            #   value: LivenessProbe
          # initialDelaySeconds: 30
          # timeoutSeconds: 5
      restartPolicy: Always
