### clone of workjob http://bigpanda.cern.ch/job?json&pandaid=3958039148
### HC template draft, created on 2018-06-08.165046
###

################
##### Jobs #####
################
[jobs]
list_jobs = workjob

################################
#### Input data exploration ####
################################
[input_data_exploration]
data_exploration_method = random

### TODO FIXME ###
list_input_dspattern_identifiers =
###########################
##### workjob JobSpec #####
###########################
[workjob.jobspec]

NOBUILD = True


## computingSite will be ###SITE###
job.computingSite = ###SITE###
## cloud will be ###CLOUD###
job.cloud = ###CLOUD###

## OUTPUTDATASETNAME will be ###OUTPUTDATASETNAME###

## prodDBlock will be ###PRODDBLOCK###
##        if you use "exact" input data exploration method, use dataset name of the first input file
prodDBlock = NULL

## jobName will be ###JOBNAME### generated by HC
job.jobName = ###JOBNAME###

## jobDefinitionID will be ###JOBDEFINITIONID### generated by HC
job.jobDefinitionID = ###JOBDEFINITIONID###

job.AtlasRelease =
job.homepackage =
job.transformation = buildGen-00-00-01
job.destinationDBlock = ###OUTPUTDATASETNAME###
job.destinationSE = ###SITE###
job.prodDBlock = ###PRODDBLOCK###
job.VO = atlas
job.coreCount = ###CORECOUNT###
job.currentPriority = 10000
job.cmtConfig  =
job.prodUserName = gangarbt
job.inputFileType =
job.prodSourceLabel = cost_matrix
job.processingType = cost_matrix_xrdcp



### TODO FIXME ###
FILEO00 = ###fileO00###
FILEOL00 = ###fileOL00###
### TODO FIXME ###
job.jobParameters = -i sources.ef8e80e8-94ed-466b-beaa-dcf8f2576a6d.tar.gz -o ###FILEO00### --sourceURL https://aipanda078.cern.ch:25443 -r .


#########################
##### workjob Files #####
#########################
[workjob.files]
### every property below that starts with fileID listed in list_files is a FileSpec() object attribute.
###     Attribute names are case-sensitive.
###     List of FileSpec() attribute is in PanDA client on cvmfs, as well as in https://github.com/PanDAWMS/panda-client/blob/master/pandatools/FileSpec.py#L8
### You can refer to these variable values with their names in format ###variableName### (variable name is case sensitive).
###     HC then takes the fileID's lfn value to replace it e.g. in jobParameters
###     e.g.
###     attribute fileI00.lfn:
###            fileI00.lfn = my.file.name.root
###     will be used to define variable MYINPUTFILE:
###            MYINPUTFILE = ###fileI00###
###     and job.jobParameters will then include  " ###MYINPUTFILE### "  e.g.
###             --inputEvgenFile ###MYINPUTFILE###

##########################
##### workjob Inputs #####
##########################
## first, list names of file objects
### TODO FIXME ###
## for data_exploration_method = exact, list inputs, pseudoinputs, outputs, and logs
# list_files = fileO00,fileOL00
## for data_exploration_method = random, do not list inputs, list only pseudoinputs, outputs, and logs
list_files = fileO00,fileOL00
#
## provide configuration for all input file objects
## file object configuration format:
##     fileID.field = value
## fields for inputs/pseudo_inputs: type, lfn, dataset, prodDBlock, GUID, fsize, scope, status='ready', md5sum, checksum
## fields for logs/outputs: type, lfn, dataset, destinationDBlock, destinationSE
####### N.B.: Do not set destinationDBlockToken ! HC-571
##


###########################
##### workjob Outputs #####
###########################
### file fileOL00
fileOL00.dataset = ###OUTPUTDATASETNAME###
fileOL00.destinationDBlock = ###OUTPUTDATASETNAME###
fileOL00.lfn = ###JOBNAME###.job.log.tgz
fileOL00.type = log
fileOL00.destinationSE = ###SITE###

### file fileO00
fileO00.dataset = ###OUTPUTDATASETNAME###
fileO00.destinationDBlock = ###OUTPUTDATASETNAME###
fileO00.lfn = cost_matrix.hc_###TESTID###.###SITE###.###JOBNAME###.HITS.pool.root
fileO00.type = output
fileO00.destinationSE = ###SITE###